### ISSUE TITLE
Error reported when hole is touching the outer edge

### ISSUE THREAD

**Issue by viridia** [x6ud/poly-partition-js#2]
I'm using `poly-partition` to process the output of `polygon-clipping` (https://github.com/mfogel/polygon-clipping). Unfortunately, when subtracting shapes `polygon-clipping` sometimes generates a hole which is touching (but does not go outside of) the outer edge of the contour. `poly-partition` regards this case as an error, although technically it should be legal.

Example case:

outer: `[28,36],[29.250000000000004,36],[28.95,36.3],[28.95,36.7],[29.3,37.05],[29.7,37.05],[30.05,36.7],[30.05,36.3],[29.749999999999996,36],[31,36],[31,39],[30,40],[29,40],[28,39],[28,37.75],[28.05,37.7],[28.05,37.3],[28,37.25]`
hole: `[[31,38],[30,37],[29,38],[30,39]]`

(You may also notice that polygon-clipping uses a different representation of a `point` - it uses 2-tuples rather than { x, y } - having to convert back and forth between these formats is a bit of a pain.

BTW I'm using this to generate navigation meshes for a game engine. :)

**Comment by x6ud** [comment]
Change `inCone` to this and it should work
```
function isConvexTolerance(p1: Point, p2: Point, p3: Point): boolean {
    return area(p1, p2, p3) <= 0;
}

function inCone(p1: Point, p2: Point, p3: Point, p: Point): boolean {
    const convex = isConvexTolerance(p1, p2, p3);
    if (convex) {
        return isConvexTolerance(p1, p2, p) && isConvexTolerance(p2, p3, p);
    } else {
        return isConvexTolerance(p1, p2, p) || isConvexTolerance(p2, p3, p);
    }
}
```

I'm not sure if this will cause other problems so I'm not going to change it for now, but it at least passes the current test set
You can copy and modify it yourself to better fit your project's point data format so it can run faster 👌

**Comment by viridia** [comment]
Thanks, I will try that! :)

**Comment by viridia** [comment]
Yes, that works. Closing.
